name: Deploy to Elastic Beanstalk

on:
  push:
<<<<<<< HEAD
    branches: [master]
=======
    branches: [main]
>>>>>>> 068efe9fc09fd05b2a2370ec181329eb22c2f141

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x "*.git*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: port-api
          environment_name: Port-api-env
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
